### ISSUE TITLE
Problems 

### ISSUE THREAD

**Issue by rmulr** [shashlik/shashlik-runtime-env#24]
Hey there,

possible the project is dead? Anysways i tried running WhatsApp.apk through Shashlik but run into the following problems

The App Window starts with a black window and hangs.

How do i fix this?

> Created filesystem with 11/4224 inodes and 1302/16896 blocks
> Failed to create Context 0x3005
> emulator: WARNING: Could not initialize OpenglES emulation, using software renderer.
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/shashlik/bin/shashlik-run", line 119, in send_icon
>     with open(icon_path, "rb") as icon:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.local/share/shashlik/WhatsApp.apk.png'

**Comment by shahanurrhmn** [comment]
There is an alternative solution for this issue is to buy a comfortable new Smartphone.
