### ISSUE TITLE
App installing Problem

### ISSUE THREAD

**Issue by mistrysiddh** [shashlik/shashlik-runtime-env#25]
> root@kaneki-ken:~/Downloads# uname -a
> Linux kaneki-ken 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali1 (2018-01-08) x86_64 GNU/Linux
> root@kaneki-ken:~/Downloads# ls
> insta.apk
> root@kaneki-ken:~/Downloads# /opt/shashlik/bin/shashlik-install insta.apk
> Successfully installed Instagram
> Traceback (most recent call last):
>   File "/opt/shashlik/bin/shashlik-install", line 109, in <module>
>     message ("Successfully installed %s" % app_name)
>   File "/opt/shashlik/bin/shashlik-install", line 22, in message
>     "--msgbox", msg])
>   File "/usr/lib/python3.6/subprocess.py", line 267, in call
>     with Popen(*popenargs, **kwargs) as p:
>   File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'kdialog': 'kdialog'
> root@kaneki-ken:~/Downloads#

**Comment by arashsoftco** [comment]
same problem
